[tools]
vasc = "vasc-rbx/vasc@2.0.24"
stylua = "JohnnyMorganz/stylua@2.3.1"
selene = "Kampfkarren/selene@0.30.0"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.5.1"
